---
- name: Ensure app directory exists
  file:
    path: /opt/url-shortener-app
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy docker compose file
  copy:
    src: docker-compose.yml
    dest: /opt/url-shortener-app/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Install systemd service
  template:
    src: app.service.j2
    dest: /etc/systemd/system/url-shortener.service
    mode: '0644'

- name: Ensure app service is started and enabled
  systemd:
    name: url-shortener.service
    state: restarted
    enabled: true