- name: Install and Configure apps
  hosts: web
  become: true
  roles:
    - role: users
    - role: docker
    - role: exporters
    - role: grafana-stack
    - role: prometheus
    - role: firewall
    - role: app
    - role: maintenance
    # - role: test
