---
- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Deploy Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: '0644'

- name: Ensure Prometheus service is started and enabled
  ansible.builtin.systemd:
    name: "{{ prometheus_service }}"
    state: restarted
    enabled: true
